Repository codelicia/trineforce, pull requests merged in 2019-11, with the labels that each got.

#11 Fix false-negative when updating a record
  src/Soql/ConnectionWrapper.php
Labels: bug

#13 Send headers on subrequests
  src/Soql/ConnectionWrapper.php
Labels: bug, enhancement

#16 composer req symplify/changelog-linker --dev
  CHANGELOG.md
  changelog-linker.yml
  composer.json
Labels: documentation, enhancement

#15 Enable SQL Logger
  src/Soql/ConnectionWrapper.php
Labels: enhancement, good first issue
